### PR TITLE
Add files and readme for docker image

### PR DESCRIPTION
**Pull request by whatwareweb**
This PR is the docker image files.

### CODE REVIEW

**Comment by whatwareweb** [comment]
I'm pretty sure all the docker image stuff here is complete now!

**Comment by whatwareweb** [comment]
OK now it's complete for real this time

**Review by grymmy — CHANGES_REQUESTED** [review]
Hmm - couple issues I think:

1. The desire here is to compile your potentially dirty spade repo (with changes) within the docker environment.  Right now, it appears as though this is just compiling the spade repo that is cloned within the docker image, and the volume that is mounted seems only to be used to copy the uf2 back to the local filesystem
2. This did not work by default on OSX - specifically, had difficulties installing chcon, and also was not able to trivially set up docker to pass the whoami check in build-with-docker.sh

**Comment by grymmy** [comment]
For the record - with a few modifications to work around the issues I experienced, I _was_ able to compile spade w/ this, which is wicked cool!

**Comment by whatwareweb** [comment]
So to clarify, the repositories should be cloned at runtime rather than buildtime?

Also, for Mac, i'm not sure as I don't have a mac to test, but chcon might not even be needed, it is just there to prevent SELinux from stopping the volume mount with docker.

**Comment by grymmy** [comment]
> So to clarify, the repositories should be cloned at runtime rather than buildtime?

The spade directory wouldn't need to be cloned at all, ideally - it would just use the one on your local machine (and it might have non-committed hot changes).  It would also be fine if the script did a completely 100% clean rebuild every time you ran it (i.e. can just punt on incremental compilation if u want)

**Comment by whatwareweb** [comment]
OK, changed the docker image to build from currently cloned directory.

Also added a line in the docker image README about Mac maybe commenting out the chcon line, if you could test if that works that would be great.
The reason this line is there is to fix SELinux permission issues I was having on Linux.

**Comment by grymmy** [comment]
Will look at this in detail today when I have time - excellent work!

**Review by JosiasAurel — APPROVED** [review]

**Review by grymmy — APPROVED** [review]
Awesome!

**Pull request merged**
